# Get basic robot information

---
bool success
string message
string version           # Controller version
string type             # Robot model
string sdk_version      # xCore SDK version
# float64[] joint_positions  # Current joint angles [rad]
# float64[] cartesian_pose   # Current Cartesian pose [x, y, z, rx, ry, rz]
