# Request
string register_name
string data_type    # Options: "float", "int", "bool", "int16", "uint16", "double"
int32 index         # Index when reading a single value
bool read_all       # Whether to read all values

---
# Response
bool success
string message

# Return arrays by data type
float32[] float_values
bool[] bool_values
int16[] int16_values
float64[] double_values
